ARG PYTHON_VERSION=3.13
FROM python:${PYTHON_VERSION}-slim

RUN apt-get update -qq && \
    apt-get install -qq -y --no-install-recommends gcc libc-dev > /dev/null 2>&1 && \
    rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir \
    ruff mypy vulture \
    pytest pytest-asyncio pytest-cov \
    httpx firebase-messaging homeassistant \
    "python-socketio[asyncio_client]>=5.12.0" \
    av pymediasoup Pillow numpy PyTurboJPEG \
    && pip install --no-cache-dir aiodns pycares

WORKDIR /app
