ARG PYTHON_VERSION=3.12
FROM python:${PYTHON_VERSION}-slim

RUN apt-get update -qq && \
    apt-get install -qq -y --no-install-recommends gcc libc-dev > /dev/null 2>&1 && \
    rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir \
    ruff mypy vulture \
    pytest pytest-asyncio pytest-cov \
    httpx firebase-messaging homeassistant \
    "python-socketio[asyncio_client]>=5.12.0" \
    "av==13.1.0" pymediasoup Pillow \
    && pip install --no-cache-dir "aiodns==3.2.0" "pycares==4.4.0"

WORKDIR /app
