FROM python:3.12-slim

RUN pip install --no-cache-dir \
    ruff mypy \
    pytest pytest-asyncio pytest-cov \
    httpx firebase-messaging homeassistant \
    "python-socketio[asyncio_client]>=5.12.0" \
    "av==13.1.0" pymediasoup Pillow \
    && pip install --no-cache-dir "aiodns==3.2.0" "pycares==4.4.0"

WORKDIR /app
